USE MuOnline97

TRUNCATE TABLE AccountCharacter
TRUNCATE TABLE Character
TRUNCATE TABLE DefaultClasstype
TRUNCATE TABLE ExtWarehouse
TRUNCATE TABLE GameServerInfo
TRUNCATE TABLE GoldenCoin
TRUNCATE TABLE Guild
TRUNCATE TABLE GuildMember
TRUNCATE TABLE MEMB_INFO
TRUNCATE TABLE MEMB_STAT
TRUNCATE TABLE OptionData
TRUNCATE TABLE RankingBloodCastle
TRUNCATE TABLE RankingDevilSquare
TRUNCATE TABLE ResetInfo
TRUNCATE TABLE warehouse